"""Environment-backed configuration for validator redundancy services."""

import os


DEFAULT_CHECKPOINT_DIR = os.getenv("VALIDATOR_CHECKPOINT_DIR", "/tmp/beam-validator")
CHECKPOINT_INTERVAL_SECONDS = int(os.getenv("CHECKPOINT_INTERVAL_SECONDS", "300"))
MAX_CHECKPOINT_AGE_HOURS = int(os.getenv("MAX_CHECKPOINT_AGE_HOURS", "24"))
MAX_CHECKPOINTS_KEPT = int(os.getenv("MAX_CHECKPOINTS_KEPT", "10"))

HEALTH_CHECK_INTERVAL_SECONDS = int(os.getenv("HEALTH_CHECK_INTERVAL_SECONDS", "30"))
UNHEALTHY_THRESHOLD_FAILURES = int(os.getenv("UNHEALTHY_THRESHOLD_FAILURES", "3"))
CRITICAL_THRESHOLD_FAILURES = int(os.getenv("CRITICAL_THRESHOLD_FAILURES", "5"))

MAX_RECOVERY_ATTEMPTS = int(os.getenv("MAX_RECOVERY_ATTEMPTS", "3"))
RECOVERY_BACKOFF_SECONDS = int(os.getenv("RECOVERY_BACKOFF_SECONDS", "60"))
